format = """
[â–‘â–’â–“](#c4a7e7)\
[ ğŸ—¿ ](bg:#c4a7e7 fg:#090c0c)\
[î‚´](bg:#9c27b0 fg:#c4a7e7)\
$directory\
[î‚´](fg:#9c27b0 bg:#6b46c1)\
$git_branch\
$git_status\
[î‚´](fg:#6b46c1 bg:#4c1d95)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#4c1d95 bg:#2d1b69)\
$time\
[î‚´ ](fg:#2d1b69)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#9c27b0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#6b46c1"
format = '[[ $symbol $branch ](fg:#9c27b0 bg:#6b46c1)]($style)'

[git_status]
style = "bg:#6b46c1"
format = '[[($all_status$ahead_behind )](fg:#9c27b0 bg:#6b46c1)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#4c1d95"
format = '[[ $symbol ($version) ](fg:#9c27b0 bg:#4c1d95)]($style)'

[rust]
symbol = "î¨"
style = "bg:#4c1d95"
format = '[[ $symbol ($version) ](fg:#9c27b0 bg:#4c1d95)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#4c1d95"
format = '[[ $symbol ($version) ](fg:#9c27b0 bg:#4c1d95)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#4c1d95"
format = '[[ $symbol ($version) ](fg:#9c27b0 bg:#4c1d95)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2d1b69"
format = '[[ ïº $time ](fg:#b794f6 bg:#2d1b69)]($style)'